version: "3.8"

services:
  db:
    image: mysql:5.6
    platform: linux/amd64
    container_name: bd_symfony_hello_mariage
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: 'admin'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_symfony_hello_mariage
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  php:
    build:
      context: ./.docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: php8_symfony_hello_mariage
    ports:
      - "8081:80"
    volumes:
      - ./.docker/apache:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
